stages:
#  - tests
  - deploy

#unit_and_integration_tests:
#  image: python:3.7-windowsservercore-1803
#  stage: tests
#  before_script:
#    - pip install pipenv
#    - pipenv install --dev
#    - pipenv install
#  script:
#    - pipenv run pylint  sample/
#    - pipenv run pycodestyle . --max-line-length=100
#    - pipenv run pydocstyle .

deploy_to_github:
  image: python:3.7-alpine3.7
  stage: deploy
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apk add --update --no-cache openssh git )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "cardwellshayne@gmail.com"
    - git config --global user.name "cardwellshayne"
  script:
    - git remote add git_origin $SSH_PROJECT_URL
    - git checkout master
    - git checkout --orphan latest_branch
    - git add -A
    - git commit -am "Deploying to GitHub"
    - git branch -D master
    - git branch -m master
    - git push -f git_origin master
